/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.anurag.firebaseauthflow.api.client.model


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param status Request status
 * @param message Response message, if any
 * @param errors errors, if any. Will contain errors, if status===false
 */


data class ApiResponseModel (

    /* Request status */
    @Json(name = "status")
    val status: kotlin.Boolean,

    /* Response message, if any */
    @Json(name = "msg")
    val message: kotlin.String,

    /* errors, if any. Will contain errors, if status===false */
    @Json(name = "errors")
    val errors: kotlin.collections.List<kotlin.String>? = null

)

