/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.anurag.firebaseauthflow.api.client.model

import com.anurag.firebaseauthflow.api.client.model.ContentModelContent

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Object containing contents for the userId
 *
 * @param id 
 * @param content 
 */


data class GetContentResponseData (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "content")
    val content: ContentModelContent

)

